@startuml
'https://plantuml.com/class-diagram

class Layers




interface ILayer

interface Transformable{
    + move(pos: Vector2D)
    + resize(size: Size)
}


interface PixelWritable<Pixels, Convert>{
    + write(
        frame_buff: &mut [u8],
        pos: &Vector2D<usize>,
        pixel_color: &PixelColor
    ) -> KernelResult
}


interface LayerDrawable<Pixels,Convert>{
    + draw(
     pixel_writer: PixelWritable,
     window_state: WindowState
     )
}



Layers "0..n" o--> ILayer



LayerDrawable --> PixelWritable



ILayer ..|> Transformable
ILayer ..|> LayerDrawable


class PlainLayer{}
class CursorLayer{}
class WindowLayer{}


@enduml